name: Setup Environment
description: "Installs dependencies and generates protobuf files"

runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.23'
        check-latest: true
        cache-dependency-path: '**/*.sum'

    - name: verify go version
      run: go version
      shell: bash 

    - name: Install protoc
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
      shell: bash
    
    - name: Install protogen plugins
      id: protogen-cache
      uses: actions/cache@v4
      with:
        path: |
          ~/go/bin/protoc-gen-go
          ~/go/bin/protoc-gen-go-grpc
        key: ${{ runner.os }}-protocgen-${{ hashFiles('**/go.sum') }}

    - name: Install protoc-gen-go protoc-gen-go-grpc
      if: steps.protogen-cache.outputs.cache-hit != 'true'
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      shell: bash

    - name: Regenerate proto files
      run: ./scripts/regen_proto.sh
      shell: bash
