name: Go build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23'
          check-latest: true
          cache-dependency-path: '**/*.sum'

      - name: verify go version
        run: go version

      # Install dependencies
      - name: Install dependencies
        # run: go mod tidy
        run: make tidy

      - name: Run tests
        # run: go test -v -timeout 30s -cover ./...
        run: make test ARGS="-v"
