name: 'Lint PR'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened

jobs:
  semantic-pr:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      statuses: write # needed when use wip
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_PAT }}
        with:
          wip: true
