name: 'Lint PR'

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  merge_group:
    types:
      - checks_requested # when use merge group

jobs:
  semantic-pr:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      statuses: write # needed when use wip
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          wip: true
